### ISSUE TITLE
"Invalid date" when user has never logged in

### ISSUE THREAD

**Issue by alalonde** [convergencelabs/convergence-project#111]
<img width="1178" alt="admin-console" src="https://user-images.githubusercontent.com/1402582/80989545-4fe17880-8df2-11ea-8697-12367ba6c7aa.png">

I would expect to see either a blank column or something like "never"

**Comment by mmacfadden** [comment]
Is this the domain users screen?

**Comment by alalonde** [comment]
Yes.
