### ISSUE TITLE
Add permissions to Activity

### ISSUE THREAD

**Issue by mmacfadden** [convergencelabs/convergence-project#161]
**Versions**
 - Convergence Version: 1.0.0-rc.7

**Description**
Activities should have permissions to join just like Chats.  An activity should be able to be public (default for backwards compatibility) where anyone can join, or private where you need to be part of a group that has permissions, or be a user that has permissions to join.

**Is there a workaround in the absence of this feature?**
No.

## Breaking Change
This will be a breaking change because Activities could previously be joined by any user. Code that assumes any user can join any activity may need to be updated.

Additionally, activities now must be created before they can be joined. This is because we need a persistent entity to attach permissions to. 

```js
domain.activities()
  .create({
    activityType: "my-type",
    activityId: "my-id",
    worldPermissions: ["join", "set_state", "view_state"]
  })
  .then(() => console.log("activity created));
```

```js
domain.activities()
  .remove("my-type", "my-id",)
  .then(() => console.log("activity removed));
```

To maintain a semblance of backwards compatibility, we have added the ability to auto create collections when joining. The first user that joins will cause the activity to be created. Similarly, you can make the Activity ephemeral and it will be removed when the last user leaves.  If you properly set the world permissions, you can achieve similar functionality as in prior releases:

```js
const options = {
  autoCreate: {
    ephemeral: true,
    worldPermissions: ["join", "view_state", "set_state"]
  }
};

domain.activities()
  .join("project", "myProject", options)
  .then((activity) => {
    // interact with the activity.
  });
```

**Comment by CedricFR** [comment]
+1 on this idea.
As part of those permissions I'd love to have a parameter to allow/prevent access to other participants' state in the activity.

Use case being: a facilitator launches an activity where all other sessions participate (update their states). The facilitator has access to all their updates, but other participants can't see each other's updates.

**Comment by mmacfadden** [comment]
Thanks for the input, that is a great idea.

**Comment by mmacfadden** [comment]
This has been implemented
