### ISSUE TITLE
Return indication that Anonymous Authentication is disabled instead of Authentication Error

### ISSUE THREAD

**Issue by toebes** [convergencelabs/convergence-project#177]
**Versions**
 - Convergence Version: 1.0.0-rc.7
 - OS: Windows 10
 - Browser: Chrome
 - Java Version: openjdk 12-ea 2019-03-19

**Describe the Bug**
If you attempt to connect to a domain Anonymously, it generates the error:
14:31:19 ERROR DomainActor - DomainActor(convergence/scienceolympiad): Authentication failed

**Step To Reproduce**
*A code snippet or gist to reproduce the issue will greatly improve our response time*
1. Create a new domain called newdomain and make sure that Anonymous Authentication is disabled
```
Convergence.connectAnonymously("http://mydomain.com/api/realtime/convergence/newdomain")
            .then((domain: ConvergenceDomain) => {
                console.log("success.");
            })
            .catch((error) => {
                console.log("Could not connect: " + error);
            });
```
**Expected Behavior**
While it makes sense to not return information which might allow a hacker to figure out userid/password pairs, in this case connecting Anonymously should give an indication that the setting is off.

**Comment by alalonde** [comment]
Yes, I can see this being useful. Although anonymous authentication is of course only intended for toy / test applications.
