### ISSUE TITLE
Handle undefined values in the model API.

### ISSUE THREAD

**Issue by toebes** [convergencelabs/convergence-project#179]
**Versions**
 - Convergence Version: 1.0.0-rc.7
 - OS: Windows 10
 - Browser: Chrome
 - Java Version: openjdk 12-ea 2019-03-19

**Describe the Feature**
If passing a model which has a field with a value of `undefined` the client will produce an error:

Pass a model to `openAutoCreate` where the `data` field has an object with a value of `undefined`.
```
   const modelService = domain.models();
                modelService.openAutoCreate({
                    collection: "basic",
                    data: {something: undefined}
                })

```
**Desired Behavior**
The modelService should do one of three things, possibly controlled by an option:
1. Generate an error message that states the model has an undefined value
1. Replace the undefined value with a blank string or other similar default
1. Delete any fields which have `undefined`

**Comment by mmacfadden** [comment]
The following options will be added to the IConvergenceOptions interface that is passed to the Domain constructor or connect methods.

```javascript
  /**
   * Configures the model subsystem.
   */
  models?: {
    /**
     * Configure how data is handled within models.
     */
    data?: {
      /**
       * Determines what happens when data is supplied to an object that
       * contains a property with a value of undefined.  If set to
       * **"error"** (the default) the client will throw an error if
       * if it detects an undefined value in an object.  If set to
       * "omit", the property will simply be omitted from the
       * resultant RealTimeObject.
       */
      undefinedObjectValues?: "error" | "omit";

      /**
       * Determines what happens when data is supplied that contains
       * an array that contains **undefined** at one or more
       * indices.  If set to **"error"** (the default) the
       * client will throw an error if if it detects an undefined value
       * within an array.  If set to "null", the value will be
       * converted to **null**.
       */
      undefinedArrayValues?: "error" | "null";
    }
  }
```
