### ISSUE TITLE
Moderate Security Issue with jwt-util

### ISSUE THREAD

**Issue by toebes** [convergencelabs/convergence-project#184]
**Versions**
 - Convergence Version: 1.0.0.rc8
 - OS: Windows
 - Browser: Chrome

**Describe the Bug**

After adding `convergence/jwt-util` to our project and doing an npm audit, it reports two moderate security issues related to the use of the `hoek` package.

```
       === npm audit security report ===                        


                                 Manual Review                                  
             Some vulnerabilities require your attention to resolve             
                                                                                
          Visit https://go.npm.me/audit-guide for additional guidance           


  Moderate        Prototype Pollution                                           

  Package         hoek                                                          

  Patched in      > 4.2.0 < 5.0.0 || >= 5.0.3                                   

  Dependency of   @convergence/jwt-util                                         

  Path            @convergence/jwt-util > jsonwebtoken > joi > hoek             

  More info       https://npmjs.com/advisories/566                              


  Moderate        Prototype Pollution                                           

  Package         hoek                                                          

  Patched in      > 4.2.0 < 5.0.0 || >= 5.0.3                                   

  Dependency of   @convergence/jwt-util                                         

  Path            @convergence/jwt-util > jsonwebtoken > joi > topo > hoek      

  More info       https://npmjs.com/advisories/566                              

found 2 moderate severity vulnerabilities in 1378 scanned packages
  2 vulnerabilities require manual review. See the full report for details.

```

Looking at `convergence/jwt-util` https://github.com/convergencelabs/convergence-jwt-util/blob/master/package.json#L27 it requires a specific version of `jsonwebtoken`: 7.1.9

Walking down the reference chain we see, looking at 

- `jsonwebtoken` 7.1.9 (https://github.com/auth0/node-jsonwebtoken) requires joi : ^6.10.1
- `joi` 6.10.1 (https://github.com/sideway/joi) requires hoek : 2.x.x
- `hoek` 2.0.0 produces the advisory: https://www.npmjs.com/advisories/566 

> Versions of hoek prior to 4.2.1 and 5.0.3 are vulnerable to prototype pollution.

Looking at the latest version of `jsonwebtoken` 8.5.1, it appears they have eliminated the dependency on `joi` completely https://github.com/auth0/node-jsonwebtoken/blob/master/package.json 

**Step To Reproduce**
1. Add jwt-util to a typescript project
2. `npm update`
3. `npm audit` to see the security issues.

**Expected Behavior**
No security audit warnings when using the package.

**Suggested Action**
Remove the specific dependency on the older `jsonwebtoken` 7.1.9 version and move to a more recent version.

**Comment by mmacfadden** [comment]
@toebes I just released v0.2.0

https://www.npmjs.com/package/@convergence/jwt-util

Can you see if that resolves the issue?
