### ISSUE TITLE
Examples stuck in "Loading" state

### ISSUE THREAD

**Issue by earshinov** [convergencelabs/convergence-project#188]
It seems that the Convergence server handling requests from the example pages is down.

**Versions**
 - Convergence Version: —
 - OS: Windows 10 x64 Version 1909 (OS Build 18363.1139)
 - Browser: Google Chrome | 86.0.4240.75 (Official Build)
 - Java Version: —

**Describe the Bug**
[Examples](https://examples.convergence.io/examples/) do not open for me.
Instead, they are stuck in "Loading" state.

For instance, the [Froala example](https://examples.convergence.io/examples/froala/?id=48d025bf-fe43-4473-b249-45dcf52faf71):
![image](https://user-images.githubusercontent.com/52021/97858285-f827b980-1d0f-11eb-9495-4a5be9f015e2.png)

**Step To Reproduce**
1. Open your browser's DevTools console
2. Open https://examples.convergence.io/examples/froala/?id=48d025bf-fe43-4473-b249-45dcf52faf71

**Expected Behavior**
The example page loads.
There are no error messages in DevTools console.

**Actual Behavior**
The example page is stuck in "Loading" state.
There is an error message in DevTools console:

```
ConsoleLogWriter.ts:48 ERROR 13:23:46.359 Handshake failed
 ConvergenceError: A request timeout occurred.
    at https://examples.convergence.io/libs/@convergence/convergence/convergence.global.js:2271:46
```

**Comment by mmacfadden** [comment]
Thank you for reporting this. We are troubleshooting the issue.
