### ISSUE TITLE
Server appears to cache permissions, ignoring updates

### ISSUE THREAD

**Issue by RanTheLab** [convergencelabs/convergence-project#193]
**Versions**

 - Convergence Version: 1.0.0-rc.7
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - Java Version: n/a

**Describe the Bug**
Adding a user to a model from the Convergence Admin Console, the user is still unable to access the model.

**Step To Reproduce**

1. Create model via API.
1. Access the model from user who does not have permissions.  `Error message: Could not open model for 14c6ac88-1625-480b-adc9-b49e1a0a731b Error:Error: Must have read privileges to open model.`
1. Use Admin Console to add that user to the model
    ![Selection_272a](https://user-images.githubusercontent.com/7691169/100967016-36c1b700-34fc-11eb-804e-c7fa5e8c2034.png)
1. Access to the model continues to be denied.
    ![Selection_273](https://user-images.githubusercontent.com/7691169/100967017-375a4d80-34fc-11eb-9288-8058f568c7bd.png)

**Expected Behavior**
Updates to users of a model in the Admin Console should immediately be reflected in the API calls.

**Comment by mmacfadden** [comment]
Greeting thanks for reporting this issue.  Do you thin this is different than the following issue:

https://github.com/convergencelabs/convergence-project/issues/1

**Comment by alalonde** [comment]
@mmacfadden I would assume just refreshing the webapp page (hence re-opening the model) would result in the permission being applied? As opposed to #1 which I take as the permission being applied immediately.

**Comment by RanTheLab** [comment]
@mmacfadden #1 does describe the situation I had when debugging a user's permission problem report.  So I can not say for sure that report is different because the user that stated something may have been done incorrectly.  A second attempt resulted in the expected behavior.  If we get more information in the future, we can revisit.
