### ISSUE TITLE
When editing an existing collection, the ant-card-head-title says New Collection

### ISSUE THREAD

**Issue by toebes** [convergencelabs/convergence-project#202]
**Versions**
*Please fill in all that apply:*
 - Convergence Version: 1.0.0-rc.7

**Describe the Bug**

**Step To Reproduce**
1. Open a domain with the convergence admin console
2. Click on Collections in the dashboard
3. Click on any existing collection.  In the and-card-head-title, it says "New Collection" even though it already exists
![image](https://user-images.githubusercontent.com/12609253/111675013-096eef80-87f3-11eb-9cce-5d82ad6b7f2e.png)

**Expected Behavior**
The title should say "Edit Collection" or some other similar text.

**Comment by mmacfadden** [comment]
Thanks for reporting this.
