### ISSUE TITLE
[WebSocket] WebSocket connection failed for Chromium based browsers

### ISSUE THREAD

**Issue by Rubix982** [convergencelabs/convergence-project#257]
**Versions**
*Please fill in all that apply:*
 - Convergence Version: 1.0.0-rc.12
 - OS: Linux
 - Browser: Google Chrome, Chromium, Brave, Opera (Chromium based browsers)
 - Java Version: openjdk 11.0.11 2021-04-20 | OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04) | OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

**Describe the Bug**
I am unable to connect to convergence's docker runtime through websockets using Chromium based browsers

**Step To Reproduce**
Follow the [quick start guide](https://convergence.io/quickstart/), and use the above mentioned browsers. The basic example/getting-started guide/code works for Firefox, but not for Chromium based browsers.

I made a relevant issue [here](https://github.com/convergencelabs/model-getting-started/issues/2) as well.

**Expected Behavior**
To work as expected.

Thanks!

**Comment by mmacfadden** [comment]
Greetings. Saw that you closed this bug.  did you find a resolution?
