### ISSUE TITLE
API documentation is not publicly available right now

### ISSUE THREAD

**Issue by Wizzerinus** [convergencelabs/convergence-project#272]
**Describe the Bug**
The link to the API documentation does not have a DNS record set for it.

**Step To Reproduce**
1. go to https://convergence.io/documentation/
2. see a link to https://api-docs.convergence.io/ and click it. You will get a "page not found" error.
3. Put the URL into dig: `dig api-docs.convergence.io` outputs an empty answer section.

I scanned other subdomains and did not find anything else that could have API docs in it.

Here are also some DNS records that cause Cloudflare 1016 error. I don't know if they're still relevant:
* demo.convergence.io
* demos.convergence.io
* examples.convergence.io
* forum.convergence.io

Seeing as the links to these pages were removed from the website, I assume they're not relevant and this point is moot, but not 100% sure.

**Expected Behavior**
Trying to open API documentation does indeed open it

**Comment by mmacfadden** [comment]
Thanks for mentioning this. We were in the process of moving things around a bit.  We updated the web site link before we got the new domain configured.  It should be fixed now. We also cleaned up some of the old domain names.  We will be working to migrate more content.
