### ISSUE TITLE
Clicking "Browse" on the Models page does not refresh the models.

### ISSUE THREAD

**Issue by mmacfadden** [convergencelabs/convergence-project#3]
Steps to recreate:

1. Create a new collection.
2. Create a model in the new collection.
3. Browse the collection in the models page.
4. In another tab create a second model in the same collection.
5. Click the browse button in the first tab.

The new model will not show up.

**Comment by alalonde** [comment]
Yes, this is a regression from the model query page / URL state refactor.  I looked into it briefly.  For any other action (e.g. filtering / searching / paging etc) the URL params change, but not for a refresh, so we'll need to either circumvent the URL state change or force-push the same URL params.

**Comment by mmacfadden** [comment]
@alalonde Thanks for the info.  When I recently refactored the collection page to support url parameters, I started from the logic we had in the models page.  I ran into a similar issue and updated the code accordingly.  Therefore, I think I might have an approach that works in the collections page.

**Comment by mmacfadden** [comment]
This has been resolved.
