### ISSUE TITLE
Add ability to query models by ID

### ISSUE THREAD

**Issue by alalonde** [convergencelabs/convergence-project#31]
Currently, when doing a `ModelService.query` you can only query *within* a model.  Thus, there's no way of simply querying by its ID, e.g. `select from collection where @id = 'foo'`. Presumably you'd need some special syntax to distinguish a model's metadata vs a field within a model.

**Comment by mmacfadden** [comment]
This has been implemented.  We added `@version` and `@id` as special fields.


```SQL
SELECT FROM test WHERE @id = "model-id";
SELECT FROM test WHERE @version = 25;
```

It is entirely possible that some one might have `@id` as a root field in the data.  In this case they can do the following:

```SQL
SELECT FROM test WHERE @@id = "model-id";
```
The double `@@` will be reduced a single `@` and the field will be looked for in the data.
