### ISSUE TITLE
Can't query for model with only user permissions

### ISSUE THREAD

**Issue by mmacfadden** [convergencelabs/convergence-project#32]
Models are not being properly returned by the query API based on permissions.

1. Create a collection called `test`
2. Create a model `test-model` in collection `test`

Then issue the query:

```
"SELECT * FROM test";
```

The model will be correctly included in the results if:

1. The collection has world read permissions.
2. Thee model overrides the collection world permissions and has world read permissions on the model.

The model will not be included (incorrectly) if:
1. The world read permissions are not set and a user specific read permission is granted.

**Comment by mmacfadden** [comment]
This has been fixed via https://github.com/convergencelabs/convergence-server/commit/dcc00b5c21467e9e7fc8a578988e4cfd152839fc

**Comment by alalonde** [comment]
Verified fix in my app.
