### ISSUE TITLE
Investigate replacement for GitBook

### ISSUE THREAD

**Issue by mmacfadden** [convergencelabs/convergence-project#45]
Since GitBook is no longer maintained we should look at alternatives.  So far candidates are:

- https://docusaurus.io/docs/en/search
- https://www.mkdocs.org/user-guide/writing-your-docs/
- https://github.com/rust-lang/mdBook

**Comment by alalonde** [comment]
@dboskovic I'm guessing you've recently gone through this... any wisdom you'd be willing to share?

**Comment by dboskovic** [comment]
We use Docusaurus 2

**Comment by mmacfadden** [comment]
We will be migrating to mkdocs-material. There is a new repository here:

https://github.com/convergencelabs/js-dev-guide
