### ISSUE TITLE
OfflineModelDownloadCompletedEvent doesn’t fire when one of the requested models is already open

### ISSUE THREAD

**Issue by alalonde** [convergencelabs/convergence-project#46]
Given an array of `modelIds`, if I already have one open and then call `domain.models().setOfflineSubscription(modelIds)`, the `Completed` event doesn't fire.

**Comment by mmacfadden** [comment]
@alalonde I made commit https://github.com/convergencelabs/convergence-client-javascript/commit/91ab0109d4cc85deb6e764a20ba33cb004b0043c . Which I think should fix this.  Can you test?

**Comment by alalonde** [comment]
Seems to be fixed.
