### ISSUE TITLE
Semantic versioning compatible schema migration engine

### ISSUE THREAD

**Issue by mmacfadden** [convergencelabs/convergence-project#58]
**Description**
The current schema migration assumes a linear migration path.  With semantic version we need to be able to support fixing schema issues in point releases, which mean when upgrading we need to have a system the can determine what patches have or have not been applied when migrating the schema.

## Example
For example:
```
- 1.0.0 -> 1.1.0:   Adds Table X
- 1.1.0 -> 1.2.0:   Adds Table y
- 1.1.0 -> 1.1.1:   Fixes a table constraint on table X
- 1.2.0 -> 1.2.1:   Fixes a table constraint on table X
- 1.2.1 -> 1.3.0:   Adds Table z 
```

**Example: 1.0.0-1.3.0**
When we are upgrading from 1.0.0 to 1.3.0, it's not as simple as to just apply all changes in sequence. We need to be able to calculate the sum total and order of database deltas that need to apply. In this case the `Fixes a table constraint on table X` is ultimately the same change, and only needs to be applied once.

**Example: 1.1.0-1.2.0**
Here we do have to apply the table x constraint fix.

**Example: 1.1.1-1.2.0**
Here we do not have to apply the table x constraint fix.

**Example: 1.1.1-1.2.0-1.2.1**
At this point, don't actually have to do anything.

So depending on the upgrade path, we may or may not have to execute certain deltas. So seemingly deltas need to have some change id. Or they have to have some ability to check for the need for themselves to be run.

We also need a system to make sure that all of the various paths lead to the same state.

**Comment by mmacfadden** [comment]
Figure 1. below shows a fictitious release timeline for a hypothetical software system. Initially the software system is released in a linear fashion. The software project is using semantic versioning.  1.0 is the initial release with 1.1 and 1.2 being enhancement releases. Then 2.0 is release which is a new major versions. 2.1 represents another enhancement release. The database schema is manage with a separate version number since not all releases include schema changes. Changes to the Database are managed with Deltas. Each Delta has a unique identifier and represents one set of logical changes.  There could be multiple deltas between single software version changes.

In our example, the system starts out in Version 1.0 with DB v1. For sake of argument, we will say **Delta A** creates this initial version from an empty database.  Software Version 1.1 includes **Delta B** which takes the database to DB v2. Software version 1.2 contains no schema changes.  Software version 2.0 comes with **Delta C** which moves us to DB v3 and software version 2.1 contains **Delta D** which moves us to DB v4. We assume that there is an audit table in the schema that is tracking which deltas have been applied and what the current DB version is.

<div align="center">
  <img width="642" alt="original-release" src="https://user-images.githubusercontent.com/1812291/86930669-dbca9600-c0fc-11ea-9465-832f3a1d87f1.png">
<p><strong>Figure 1. Software and Database Version with Deltas</strong></p>
</div>

Then, after version 2.1 is released, a bug is found in the system which includes a bug in the schema. This creates a minor release to fix the bug. Software version 2.1.1 is released containing **Delta E**, resulting in DB v5. Figure 2. below shows how **Delta E** must be backported into the system to create releases for 1.2.1 and 2.0.1, assuming that the support plan for the software system agrees to patch all current major versions and the latest release of the previous major version. Not that this creates DB v2.1 and DB v3.1 as database versions that exist "between" the normally monotonically increasing database version numbers.

<div align="center">
  <img width="631" alt="hotfix" src="https://user-images.githubusercontent.com/1812291/86930694-e553fe00-c0fc-11ea-918a-f9307f01e8f7.png">
<p><strong>Figure 2. Hot Fix and Backport</strong></p>
</div>

Figure 3. Below shows the various Deltas associated with each known Database version. We assume that when the software ships with a particular DB version, the software knows which deltas should be applied. Thus software version 2.0.1 would know that Deltas A, B, C, and E should be applied since it shipped with DB v3.1.

<div align="center">
  <img width="770" alt="db-versions" src="https://user-images.githubusercontent.com/1812291/86934202-09b1d980-c101-11ea-8e5e-3b4de65c1835.png">
<p><strong>Figure 3. Database Deltas per Version</strong></p>
</div>

Figure 4. Below shows an example updgrad path that a potential user of the system could follow.  It assumes that the first version they install is software version 1.2, which would install DB v2. Then assume they take the 1.2.1 hotfix. This will apply **Delta E** and result in a DB v2.1.

<div align="center">
<img width="711" alt="example-upgrade-path" src="https://user-images.githubusercontent.com/1812291/86932373-e554fd80-c0fe-11ea-9897-500aeecd7e30.png">
<p><strong>Figure 4. Upgrade Path</strong></p>
</div>

The interesting part comes when the user upgrades to software version 2.0. In theory they should be upgrading to version 2.0.1 or 2.1.1. But for sake of argument let's assume that for whatever reason the user does this.  The 2.0 version of the system shipped with DB v3. This version of the software knows that Delta C needs to be applied, and that it is not currently applied. Thus it will apply Delta C. However, the system can also see that Delta E was applied, but version 2.0 of the software has no knowledge of Delta A. So while normally software version 2.0 would maintain DB v3, we are somewhat in DB v3+, the "+" referencing additional deltas.  This is actually DB v3.1, but software version 2.0 has no knowledge of DB v3.1.

Finally the user migrates to software version 2.1.1. This version knows that Deltas A, B, C, D, and E should be applied.  Only D is missing, so **Delta D** is applied arriving at DB v5.  Note that we essentially skipped over DB v4.

To make this work, every delta must have a unique identifier that does not change regardless of when it is packaged. In this case "Delta E" must have the same identifier across the back port, so that it can be recognized by later versions. We will probably use identifiers like `add_user_group_class.yaml` or `create_value_id_index.yaml`. Such that the deltas are easier to scan. It may also be a good idea to prefix them with a date, to understand better the order in which they were created.  For example `2020_03_12_add_user_email_field.yaml`. This way the deltas will be time ordered, and meaningfully named.

Normally, Deltas should be applied "in order".  The system should detect when things are not as expected. It would probably be wise to set a "backport flag" on a Delta that is backported into the software, so that the system can recognize that it is ok that it exists but is not known, or that it was applied out of order. when we finally arrive that the point in the version history where the delta was backported FROM, the system could remove the backport flag.

**Comment by alalonde** [comment]
Couple of initial comments / questions.

1. Are we just talking about domain databases, the Convergence database, or both?
1. In the examples where changes can be omitted (e.g. `1.1.1-1.2.0-1.2.1`), is there any harm in just applying all the changes even if they are not needed?
1. Aren't deltas sometimes dependent on the original state of the database, such that a backported delta (e.g. delta E above) wouldn't necessarily be the same depending on which version of the database it's being applied to?

**Comment by mmacfadden** [comment]
@alalonde 

In general, the stuff that is in the original issue, is some what old thinking, but left there for history. The first comment is really where the design is.

1. We are talking about both. We will use the same mechanism for both types of database.
2. Yes, there would be harm. The changes would fail.  For example if a delta is going to create a new "table" with a "create table", if that table already exists, I can't create it again. If you try to run it again, it would result in an error. And it's not really safe to try to make the deltas idempotent, in the sense that I don't want to ignore such an error because you can't distinguish between an error you should gloss over, version a bad delta.
3. That is a good point. I have to think about that a little bit more. The backported delta needs to be "semantically" identical, but could be syntactically different. For example.  I have ClassA then I rename it in delta 1 to ClassB, then I add a property to class B in delta 2.  Delta 2 targets a property on ClassB.  If I want to back port that I need to change the delta to target ClassA, but I still need to know then, that the semantically has happened, because when I then rename Class A to Class B, Class B is now in the desired state, and I don't need to apply Delta 2.  There is some complexity there to consider.

**Comment by mmacfadden** [comment]
@alalonde 
Regarding point three.  I think the design accounts for that.  If I create a delta in the current development version, it will be checked into the code base and apply to the current state of the latest schema. It is given an id, as specified.  When we back port that we would be adding that backport to a branch at an earlier point in the code base, where that delta does not exist.  So when we back port it, we can modify it as needed to apply to the version of the schema that that version of the software would be dealing with. When the software roles forward the actual content of that delta might be different, but that should not matter since that delta is not going to be run again anywya.

Does this make sense?

**Comment by mmacfadden** [comment]
Also, I think it will be VERY rare that we need to backport a schema change and if we do we need to be pretty careful. A back ported schema change has to 1) work with versions of code that do and don't have the change, since upgrade paths can be unpredictable, 2) must be certain that they don't break other deltas, and 3) really should not require code changes (e.g. forward and backward compatible).

So I think that we probably should not over-engineer that portion of the solution right now.

**Comment by alalonde** [comment]
> Regarding point three. I think the design accounts for that. If I create a delta in the current development version, it will be checked into the code base and apply to the current state of the latest schema. It is given an id, as specified. When we back port that we would be adding that backport to a branch at an earlier point in the code base, where that delta does not exist. So when we back port it, we can modify it as needed to apply to the version of the schema that that version of the software would be dealing with. When the software roles forward the actual content of that delta might be different, but that should not matter since that delta is not going to be run again anyway.

So the delta's contents may be different depending on what it's being applied to. Yes, makes sense. And to be clear, a backport would only be created for the most reason minor version of every supported major version? Meaning we have to enforce folks getting "up to date" potentially on non-major versions before allowing these backports to be applied.

**Comment by mmacfadden** [comment]
Yes that would be correct. Assuming we are following good semantic versioning practices.

**Comment by mmacfadden** [comment]
We added a "tag" concept to the delta records to that you could see that a delta was a "variant" associated with a particular back port. We also wound up using the tag to store the deltas that are "implicitly" installed when a fresh schema in installed. That is to say the fresh install is a summation of all the deltas that came before it. When logging the deltas in the system we store the tag as well as the version of the schema that was being migrated to when the delta was installed.

We also added a schema version log that tracks what versions of the schema have been installed / upgraded to, over time.
