### ISSUE TITLE
Chat pagination is broken

### ISSUE THREAD

**Issue by mmacfadden** [convergencelabs/convergence-project#73]
**Versions**
 - Convergence Version: 1.0.0-rc.4

**Describe the Bug**
The chat screen only shows 11 chats.

**Step To Reproduce**
*A code snippet or gist to reproduce the issue will greatly improve our response time*
1. Create more that 11 chats.
2. Visit the chat screen of the domain.
3. Visit the second page.

There will only be one item

**Expected Behavior**
There should be more than one item on the second page.

**Comment by mmacfadden** [comment]
@hdyngd  FYI.

**Comment by mmacfadden** [comment]
This has been fixed and will be released in 1.0.0-rc.5

**Comment by mmacfadden** [comment]
@hdyngd is this one working for you now also?

**Comment by hdyngd** [comment]
@mmacfadden Yes. It's working. Thank you very much!!
