### ISSUE TITLE
Unable to download rxjs.umd.min.js from docker container

### ISSUE THREAD

**Issue by aaronbabaron** [convergencelabs/convergence-project#86]
Hey everyone, I've followed the quick start to the T in my application, but am unable to download rxjs.umd.min.js. I am able to download convergence.js from the docker container, though. With rxjs, it just gives me a 404.

The head in my index.html looks like this:
(github keeps formatting it strange if i post the entire thing)

`
    <script src="http://localhost:8000/client/rxjs.umd.min.js"></script>
    <script src="http://localhost:8000/client/convergence.js"></script>
`

I ran this command
`docker run -p "8000:80" --name convergence convergencelabs/convergence-omnibus`

**Comment by mmacfadden** [comment]
Thanks for reporting the issue.This is a bug in our documentation.  I will get this corrected.

Check out this index.html from one of our tutorials:

https://github.com/convergencelabs/model-getting-started/blob/master/index.html

You can instead hotlink (or include) rxjs directly:

```
<script src="https://cdn.jsdelivr.net/npm/rxjs@6.5.4/bundles/rxjs.umd.min.js"></script>
```

**Comment by mmacfadden** [comment]
Let us know if this fixes your issue.  I'll leave this open until we update the quick start (hopefully this weekend).

**Comment by aaronbabaron** [comment]
Thanks for the quick response! It fixed that issue, but now I see `exports is not defined` which points here 
![Screen Shot 2020-03-28 at 6 53 54 PM](https://user-images.githubusercontent.com/15972357/77838108-89550300-7125-11ea-898c-392ae8ac3893.png)

**Comment by aaronbabaron** [comment]
Added a global exports object, but now am getting a "require is not defined" error. Is this supposed to be happening? I'm a bit confused

**Comment by mmacfadden** [comment]
Ahh. Similar issue. You are importing the `commonjs` module.  

The convergence import should be:

```
<script src="https://cdn.jsdelivr.net/npm/@convergence/convergence@1.0.0-rc.5/convergence.global.min.js"></script>
```

Take a look at the example linked above. I think that has the correct imports.

**Comment by mmacfadden** [comment]
In `rc.5` we refactored the packaging a bit, we went and update the code associated with this tutorial in github, but apparently we missed the quick start page. So it is pointing to files that are no longer there, or are there but are different.

**Comment by aaronbabaron** [comment]
ahh thank you! no errors anymore :) thanks for responding so quickly on a weekend

**Comment by mmacfadden** [comment]
No problem. Sorry for the documentation error. If you need some pointers feel free to use the community forum. Or... we just launched a community slack channel.  It's not quite announced yet. But it is live here:

https://slack.convergence.io/

**Comment by aaronbabaron** [comment]
Wow I'll definitely join that. Thanks again for all your help!
