### ISSUE TITLE
Convergence User Permissions Ignored by Admin Console

### ISSUE THREAD

**Issue by mmacfadden** [convergencelabs/convergence-project#87]
**Versions**
 - Convergence Version: 1.0.0-rc.5

**Describe the Bug**
In the admin console, you can assign roles to users (Developer, Domain Admin, and Server Admin).  However it seems like assigning the roles makes no impact on what the user can do.

**Step To Reproduce**
*A code snippet or gist to reproduce the issue will greatly improve our response time*
1. Start the omnibus container.
2. Log in and create a new convergence user and assign them as a Developer.
3. Log out and log back in as that new user.
4. Navigate to the convergence users section.

You will see that you can still see / edit users.

**Expected Behavior**

- A server admin should be able to create, delete, edit all domains and should be able to manage convergence users.
- A domain admin should be able to create, delete, edit all domains but not manage users.
- A developer should only have access to the domains they create in their personal namespace (if enabled) and other domains they have been given permissions too.

A domain admin / developer should not even see the convergence users admin functionality.

**Comment by mmacfadden** [comment]
This is been implemented.  @alalonde can you take a look and test?

**Comment by alalonde** [comment]
As a `developer`, when I click into a domain I just created, I get the error "Error Loading Domain
Unknown error loading domain."

**Comment by mmacfadden** [comment]
@alalonde What does this have to do with this issue?

**Comment by alalonde** [comment]
The underlying assumption is that `Developer`s don't have the appropriate permission to be able to access their domain.  Is https://github.com/convergencelabs/convergence-project/issues/96 addressing that ? If so we can close out this issue.

**Comment by mmacfadden** [comment]
This issue is specifically focused on the fact that the Admin UI allowed non-admin users to change user permissions.  I believe that issue has been rectified.  the issue in your comment is unrelated to this issue. I think that, that issue was caused by #95 and #96 which have both been fixed as well.

**Comment by mmacfadden** [comment]
This has been fixed.
